### ISSUE TITLE
🐞: Xcode build error with 4.0.0 release: 'react_native_notificare_push-Swift.h' file not found

### ISSUE THREAD

**Issue by mikkoseppa** [Notificare/notificare-sdk-react-native#97] opened 2024-10-11 07:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After installing 4.0.0 versions of the react-native-notificare packages, I get a build error in Xcode for every Notificare library:

- For the file `react_native_notificare_push/NotificarePushModule.mm` I get error `'react_native_notificare_push-Swift.h' file not found`
- For the file `react_native_notificare_geo/NotificareGeoModule.mm` I get error `'react_native_notificare_geo-Swift.h' file not found`
- ...and so on. The same error repeats for **every** Notificare library that try to import that Swift bridging header.

I checked the derived data folder for build output, and seems like the bridging header is in fact generated successfully. For some reason Xcode can't still find it.
![notificare_bug](https://github.com/user-attachments/assets/276598df-701c-4699-b8b6-0632c06a723b)

I can fix the problem by replacing the import statements in all Notificare libraries from this syntax:
`#import "react_native_notificare_geo-Swift.h"`
to this:
`#import "react_native_notificare_geo/react_native_notificare_geo-Swift.h"`

After that Xcode can find the bridging headers and I can build all the libraries without any issue. Not sure why using this syntax works, but not the one without the subdirectory included. 🤷‍♂️

The previous react-native-notificare version 3.11.0 builds just fine.

### Steps to reproduce

1. Install 4.0.0 versions of react-native-notificare, react-native-notificare-geo, react-native-notificare-in-app-messaging, react-native-notificare-push, react-native-notificare-push-ui using yarn.
2. Run pod install
3. Build project In Xcode

### Expected behaviour

Project builds successfully

### Library version

4.0.0

### Operating system

iOS

### React Native version

0.72

### Additional context

Cocoapods version: 1.15.2
Xcode version: 16.0
Using old RN architecture

**Comment by hpinhal** [comment] 2024-10-11 10:02
Hi @mikkoseppa,

We created a brand new app that uses React Native 0.72.17 and the Notificare libraries you mentioned but cannot reproduce what you're describing. The app builds and runs successfully.

Can you create a new app and follow the same steps to check if you are still getting an error? 
If you can reproduce the error in a clean project, please share the project with us so we can investigate further.

Should you need to share confidential information, we recommend contacting support@notifica.re instead.

**Comment by mikkoseppa** [comment] 2024-10-11 13:39
> Hi @mikkoseppa,
> 
> We created a brand new app that uses React Native 0.72.17 and the Notificare libraries you mentioned but cannot reproduce what you're describing. The app builds and runs successfully.
> 
> Can you create a new app and follow the same steps to check if you are still getting an error? If you can reproduce the error in a clean project, please share the project with us so we can investigate further.
> 
> Should you need to share confidential information, we recommend contacting [support@notifica.re](mailto:support@notifica.re) instead.

Hi @hpinhal. Okay, so confirmed that this error happens only if you link Cocoapods libraries as static frameworks. I confirmed this with a clean RN project.

By adding this configuration to your podfile you will get the error:
`use_frameworks! :linkage => :static`

In the previous release there was no problem using that linking method in Cocoapods.

**Comment by hpinhal** [comment] 2024-10-11 13:49
Hi @mikkoseppa,

Thanks for digging into this!

The new 4.0.0 libraries adopted the new React Native plugin structure to support both old and new architectures.
We'll investigate what changed there that could affect this. I'll get back to you when I have more information.

In the meantime, I would suggest avoiding static linking if possible or continuing to use 3.11.0 for the time being.

**Comment by hpinhal** [comment] 2024-10-30 16:57
Hi @mikkoseppa,

We just released version 4.0.1.
This version fixes the import headers when building with `ENV['USE_FRAMEWORKS']`.

I'm closing this issue. Feel free to re-open it if the problem persists.

**Closed by hpinhal** 2024-10-30 16:57 UTC
Labels: bug, triage
